version: '2'

services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cinemac
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - 8888:80
          
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_DB=cinemac
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234